// <auto-generated />
namespace Vidracaria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Vidracaria10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vidracaria10));
        
        string IMigrationMetadata.Id
        {
            get { return "201703291309336_Vidracaria-1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
